### ISSUE TITLE
Common exception handling approach

### ISSUE THREAD

**Issue by tmarkovski** [streetcred-id/agent-framework#42]
We need a standard way of throwing or handling exceptions in the SDK. Some points for discussion:

1. When is an exception considered non-fatal and can be handled without throwing
2. Should exceptions be thrown when retrieving single records that don't exist? Ex: `IConnectionService.GetAsync()`.
3. Should we wrap common exceptions? Ex. catch ArgumentNullException and wrap in SDK exception?
4. Type per exception or single exception with error code?

@tplooker @DeniSpasovski @PawelJargielo @joshhill - if you have any thoughts on this, feel free to comment.

My opinion on 2 is to throw when record doesn't exist, instead returning null. This is consistent with Indy SDK behavior and it makes sense, since in a happy path scenario, we shouldn't have non existent records.
3. Don't wrap
4. Use error codes

**Comment by tplooker** [comment]
I agree with your opinions on 2, 3 and 4.

In regards to 1, I think case by case judgment is perhaps the best approach because what constitutes a non-fatal exception is kind of driven by the execution context and its perhaps hard to apply a stronger global rule then the general statement of only throw an exception in fatal scenarios.

**Comment by tmarkovski** [comment]
Fixed with #56
